### ISSUE TITLE
Colors are off in iterm2

### ISSUE THREAD

**Issue by npearson72** [noahfrederick/vim-hemisu#6]
Hi,

Sorry to keep bothering you, but my colors are off in iterm2. I'm using the peppermint iterm port as my colors for iterm2... but vim with Hemisu is off.

Here are screenshots of iterm2 vim and mvim. Mvim is correct as you see.
![screen shot 2013-09-04 at 9 32 11 pm](https://f.cloud.github.com/assets/1323414/1085873/81bf892e-15e4-11e3-981c-5936c3e31f35.png)
![screen shot 2013-09-04 at 9 32 34 pm](https://f.cloud.github.com/assets/1323414/1085874/81c1c194-15e4-11e3-979f-ef99e9f80b13.png)

**Comment by npearson72** [comment]
As a side note, vim finds the colorscheme when I'm in a vim session, and when I set it there, it works. Just not from my .vimrc file

**Comment by npearson72** [comment]
Fixed it. Turns out the order of my .vimrc commands was off. I need to do this:

  8 let &t_Co=256
  9 set background=dark
 10 set guifont=Monaco:h14
 11 colorscheme hemisu

Notice how colorscheme is at the bottom of all this?

Thanks!

**Comment by noahfrederick** [comment]
The relevant part is that you set the `'background'` option before the `:colorscheme` command. See #4 for details.
