### ISSUE TITLE
transparent background (like it is in the screenshot)

### ISSUE THREAD

**Issue by codemedic** [noahfrederick/vim-hemisu#9]
@noahfrederick lovely theme; thanks for that. I really like it.

I quite envy the transparent background in the screenshot. How did you manage that?
If it is a apple terminal app specific thing, would it be possible to add a similar setting as to one provided by solarized theme, where it leaves all / most background colours as `NONE`.

Thanks

**Comment by tamasgal** [comment]
Let me comment on this quickly: that transparency can't be handled in any VIM or shell settings/colours. This is something which is handled by the terminal application (most of them can be configured to have transparent or even blurred backgrounds). However, I don't really understand what you mean by "leaving all/most background colours as `NONE`".

**Comment by noahfrederick** [comment]
@tamasgal is right on. In this case, it's a feature of the MacVim GUI (`:help 'transparency'`). 

@codemedic, feel free to clarify what you mean. I won't add any settings, though. You can always do

``` vim
autocmd ColorScheme hemisu hi Normal guibg=NONE ctermbg=NONE
```

if you want to change the background, which works for any color scheme unlike an ad-hoc setting.

**Comment by codemedic** [comment]
Perfect; thanks @noahfrederick.

That formula worked.

![image](https://cloud.githubusercontent.com/assets/691011/13647345/8e196978-e62b-11e5-9e0b-770bab54665a.png)

**Comment by noahfrederick** [comment]
Cool.
